### ISSUE TITLE
Allows players to region without build permissions.

### ISSUE THREAD

**Issue by tlworks** [Pryaxis/TShock#1406]
So basically when you allow a person or group to a certain region, they will always have access to building/breaking in this region. I was wondering if you could add a sub option to disallow building for groups you add since it doesn't matter whether building is disabled or enabled, they will always have access.

**Comment by OnsenManju** [comment]
What permission which players are "allowed" if they can't build in that region?

**Comment by tlworks** [comment]
Entry access without building permissions.

**Comment by OnsenManju** [comment]
AFAIK, TShock's region doesn't have an ability to prohibit entering into a region to players.
Are you using region-based plugins (Smart Regions/Region Trigger/Diemob Regions etc.)?

Personally I guess your request is somewhat useful, but it's a bit weird that adding a feature to the basic behavior for the purpose of plugins in spite of nothing usable itself.

I think it should be done by plugins that can manage TShock's region without `tshock.admin.region` permission, like House Regions plugin.

Otherwise you can use Housing Districts plugin, that has own region-system and can allow/disallow trespassing on its region (maybe you already know).

**Comment by tlworks** [comment]
Yeah but I'd like to have it implemented in the Region system so we don't actually have to go about and download all sorts of plugins to set multiple areas with different regions and all chaos-like ideas. I think it would be a great idea to just include an option whether the allowed group or person is allowed to build in the ALLOWED region.

**Comment by QuiCM** [comment]
This is a request to modify the entire region system, and should really be a plugin.
