### ISSUE TITLE
Prevent/Lock banned accounts from logging in.

### ISSUE THREAD

**Issue by tlworks** [Pryaxis/TShock#1412]
This would get rid of a lot of people who try to bypass bans, for those who use a registered account.

![f272922857d83e060a8bd05ea3ced766](https://cloud.githubusercontent.com/assets/19647337/24074322/99cceaae-0c06-11e7-9704-b8a78cc128c3.png)

**Comment by Zaicon** [comment]
What's the thought process on implementing this? As it stands, there's no concept of an account being banned, only IPs. That leaves the options of either
1) If an account is associated with a banned IP, activate the lockout. This would work, but there are good chances of false positives, especially with certain ISPs/proxies that reuse IPs.
2) Create the concept of an account ban, probably by adding a column to the ban table for banned User IDs.

Even if this is implemented, there's other options to consider such as "what happens when a user (tries to) login to a banned account". I'm not entirely sure this is tShock's scope in the first place - some servers don't need this in the first place (especially if it's a simple matter of registering a new account), some want to display a message (as described in the OP), and some might want the player banned upon logging into a banned account.

That said, a nice solution to this might be creating a PlayerBanned hook, and plugin devs can handle bans (and banned accounts) however they want to.

Thoughts?

**Comment by hakusaro** [comment]
@Zaicon I would err towards option 2 and I think that's the best route

**Comment by hakusaro** [comment]
Actually, I thought about this. We have a permission for logging in, so we could just tell people to assign them to a group that negates that permission.

**Comment by bartico6** [comment]
How would that work? The login permission is checked on Guest when running the login command.

**Comment by hakusaro** [comment]
Check the login permission on the destination account too?

**Comment by hakusaro** [comment]
Nope actually any check that validates that permission is gonna have a bad time because I'm 99% sure that's the wrong context. I'm back to suggestion 2 on this.

**Comment by bartico6** [comment]
Correct, just introduce account bans.
