### ISSUE TITLE
Config summaries need to match their [Description] annotations

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1419]
There are a lot of config file line descriptions that have bad descriptions. It's worse when you look at the comment blocks above each entry because, you can see usually varied effort in them.

Each summary block should match the description as far as depth goes. In the case of developer notes, those should stay in summary blocks only. Why? These are used on the ReadMe and are auto generated -- if the information is bad in the source, it becomes unclear as to what the config settings do.

See [this line](https://github.com/NyxStudios/TShock/blob/general-devel/TShockAPI/ConfigFile.cs#L264) as an example of where the comment is better than the description.

**Comment by Enerdy** [comment]
Regarding the XML comments -- should we keep using the current styling for the summaries? By style I mean how every comment redundantly starts with the name of the property, like so:
```/// <summary>ConfigFile - The config file class, which contains the configuration for a server that is serialized into JSON and deserialized on load.</summary>```
I believe this was done because the documentation tool being used didn't write the property name along with its description.

**Comment by hakusaro** [comment]
Definitely not. That sucks. Let's change it to be more concise.

Lucas Nicodemus
http://keybase.io/xn
