### ISSUE TITLE
ChatAboveHeads Regression: Chat isn't sent to the player who sent the chat

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1440]
As Off has so rightly put it, this could be considered a very nice feature for people to have. Apparently it's quite popular on Teeria.

This should probably be a config option or debated. See https://github.com/NyxStudios/TShock/issues/1436#issuecomment-298981303 and https://github.com/NyxStudios/TShock/commit/528d9c642b08584bbeec4d1e84e992e8d0d003f8#commitcomment-22002690.

**Comment by WhiteXZ** [comment]
So the issue with chat over heads right now:
Previous version formatted correctly to everyone BUT the sending user on non-SSC. E.g., everyone else saw `<(Prefix) name (suffix)>: text`, but the sending user saw `<name>: text`.
This is because apparently we can't make a player update their own name without SSC?

The current version sends them the correct message, but not longer does an overhead chat for themselves (Everyone else sees an overhead message).

**Comment by QuiCM** [comment]
This is an issue with Terraria itself. Not a whole lot we can do
