### ISSUE TITLE
Add easy optout and text warnings for opting out of stats collection

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#1446]
Related to discussion in #high-charity, will be implemented in like 10 hours max.

**Comment by Ijwu** [comment]
I think the most basic requirements here should be:

* Provide a full stat-tracker opt-out in some place a user will edit at least once.
    * In our case, the config will work.
* Create an informational post which describes what data we collect and how we use it. 
    * It should include whether we uniquely identify servers.
    * It should include why we collect this information.
    * It should include how we collect this information and where it can be accessed, if it is accessible.
    * It should include what this information looks like.

The second point doesn't necessarily need to be present in the software. If it is not present in the software then a reasonable effort should be made to expose this information. I suggest including a small bit of text or a link in the project README, a post on the tshock.co website, as well as a page in the tshock.readme.io documentation source.

Comments?

**Comment by WhiteXZ** [comment]
A privacy policy on tshock.co would be adequate, imo.

**Comment by hakusaro** [comment]
I believe we have one of those.

**Comment by WhiteXZ** [comment]
If it includes information about the stat tracker and is easily accessible then I would consider that sufficient

**Comment by hakusaro** [comment]
It doesn't.

**Comment by WhiteXZ** [comment]
From discord, proposed addition to the privacy policy:

>TShock collects stats for the purposes of making software decisions, such as whether or not we need to work with certain game server providers to provide additional support. We also collect information like your currently running plugins and their API versions to determine if we're making API breaking changes. You can opt-out of this data collection.

**Comment by WhiteXZ** [comment]
In addition to the above, a line stating that all stat tracking is anonymous and that we do not uniquely identify servers may be wanted

**Comment by Ijwu** [comment]
I don't think that's going far enough. A quick blurb about the data collection does not give someone enough information to make an informed decision about whether they want to opt out or not.

**Comment by WhiteXZ** [comment]
I beg to differ. At a stretch I'd say a page on our documentation detailing what information is tracked could be added, but I see no need or reason to detail every scrap of what we do

**Comment by Ijwu** [comment]
@WhiteXZ Do you see it hurting the project in any way to detail these things? I volunteer to write this stuff up, I see no reason why it should explicitly be excluded.

**Comment by WhiteXZ** [comment]
Based on discussion in discord, proposed extended privacy policy:
>TShock collects stats for the purposes of making software decisions, such as whether or not we need to work with certain game server providers to provide additional support.
All data collected is anonymised and aggregated so we can improve TShock based on common usage.
The data we collect is outlined below. All data collection can be opted out of by using the `--stats-optout` command-line flag
**Server Port**
The port on which your server is listening.
**Current Players**
The number of players currently online on your server.
**Max Players**
The maximum number of players your server is set up to allow.
**System RAM**
The amount of RAM installed on the system running your server.
**Server TShock Version**
The version of TShock your server is running.
**Server Terraria Version**
The version of Terraria your server supports.
**Provider ID**
A unique identifier given to server providers so that their server data can be analysed separately if needed.
**Server ID**
A session ID generated each time your server starts, used to validate your server's stats.
This is not used to uniquely identify servers.
**Mono**
A boolean value letting us know if you're running TShock with mono or not

This lists all information currently collected. Additions to stat tracking could be made as required. Is this enough information for someone to decide whether or not they opt out?

**Comment by hakusaro** [comment]
![iphone-6-tweaks-3](https://cloud.githubusercontent.com/assets/532647/25983954/0530a0e2-36a5-11e7-85e4-5f066737564d.jpg)

So this is how iPhones do it. [Their help article](https://support.apple.com/en-us/HT202100) is also very brief.

**Comment by WhiteXZ** [comment]
For reference, something like Discord (which stores every single message you send, files uploaded, etc.) does it like this: https://discordapp.com/privacy

**Comment by WhiteXZ** [comment]
Slack does it like this: https://slack.com/privacy-policy

**Comment by hakusaro** [comment]
Ya I consider both of those documents to be completely impenetrable to humans.

**Comment by WhiteXZ** [comment]
Any more feedback on this?

**Comment by tylerjwatson** [comment]
I agree with @Ijwu.  It can't hurt to be friendly and transparent to the community which is (rightly) getting more and more paranoid about phone-home systems.  We're entering an age of technology from vendors who either aren't transparent or outright lie about the information they collect and what it's used for.  

That said, here's some pragmatic solutions that could probably satisfy both ends of the spectrum as this discussion itself is going around in circles a bit.

I propose that:

1. Software
  * On startup complete, display a _brief_ sentence about collection and usage of telemetry data, *once* on new installations:
> TShock by default collects stats for the purposes of making software decisions.  We also collect information like your currently running plugins and their API versions to determine if we're making API breaking changes. You can opt-out of this data collection.  For more information please visit http://tiny-url-of-privacy-policy
> To opt-out at any time, please type **/optout** in the console, or edit your server's configuration file.
  * An in-game, console only, command to easily opt-out of telemetry data, similar to the way /auth works.  Can be `/optout` or similar
2. Website/Correspondence
  * Information about stat collection, including what is collected, and what it is used for detailed in README.md, website and whatever else is suggested

**Comment by bartico6** [comment]
Sorry to butt into your conversation, but I thought of something while reading:
You can keep reminding the user about the opt-out until the /auth command is used, since creating the superadmin account usually signifies the user finishing configuration. Either that, or do so right after auth is used, appended to the usual "how to become admin" information, since that guarantees the superadmin reading through it.

**Comment by tylerjwatson** [comment]
@bartico6 I don't mind that at all, great suggestion

**Comment by QuiCM** [comment]
@NyxStudios/tshock Could you review https://tshock.co/xf?help/terms and provide feedback on whether this is suitable.
Additionally a console message upon deactivating the auth system, and a console command to open the system default web browser to the above link will be added

**Comment by QuiCM** [comment]
@hakusaro did this ever get implemented?

**Comment by hakusaro** [comment]
@QuiCM nothing on this has been implemented yet. Super low priority for me, tbh.

**Comment by QuiCM** [comment]
Stats is kill
