### ISSUE TITLE
NullReferenceException Spam from HandlerGetData / HandlePlayerUpdate

### ISSUE THREAD

**Issue by jujaga** [Pryaxis/TShock#1460]
**TShock Version**
4.3.24, APIv2.1, OTAPI v2.0.0.27

**Stack Trace**
> System.NullReferenceException: Object reference not set to an instance of an object.
   at TShockAPI.GetDataHandlers.HandlePlayerUpdate(GetDataHandlerArgs args)
   at TShockAPI.GetDataHandlers.HandlerGetData(PacketTypes type, TSPlayer player, MemoryStream data)

**Reproducibility**
Unfortunately I have been unable to track down the cause or source of the problem. However, I do know that this NRE spams our server's SQL logs significantly (we get on average 8000 to 10000 of these errors reported a day) and in rapid-fire succession. While it doesn't impact the users or the server stability directly, this NRE appears extensively and at random.

**Screenshot**
![capture](https://user-images.githubusercontent.com/1546326/27366185-4e3d7e4a-55f9-11e7-8926-8cc57e9d77e6.PNG)

**Comment by TeeriaLLC** [comment]
```2017-06-23 11:21:41 - GetDataHandlers: ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at TShockAPI.GetDataHandlers.HandlePlayerUpdate(GetDataHandlerArgs args)
   at TShockAPI.GetDataHandlers.HandlerGetData(PacketTypes type, TSPlayer player, MemoryStream data)```

Only happens in NSSC mode, was reported like a million times before. When will this ever get looked into/fixed.

**Comment by ProfessorXZ** [comment]
White added null checks for everything in the last release, did anyone actually have issues with this _without any plugins installed_?

**Comment by tlworks** [comment]
@ProfessorXZ Mind providing or linking me to those null checks? Perhaps certain plugins are missing these but it's quite hard to test this without any plugins due to the fact the everyone would grief without protection.

Regardless of that, I don't think this would appear without plugins.

**Comment by Commaster** [comment]
Hey dumdums, add SSC-mode checks (if (Main.ServerSideCharacter)) for these SSC-only fields:
https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/GetDataHandlers.cs#L2637
https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/GetDataHandlers.cs#L2643
https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/GetDataHandlers.cs#L2649

Enjoy stealing my fix.

**Comment by ivanbiljan** [comment]
@Commaster feel free to contribute to the project by making a pull request. This will also ensure that you are given proper credit. Thank you :)

**Comment by Commaster** [comment]
Oh really, we are talking about giving credit? Well, that wasn't the case with #781 which were blatantly stolen in 16cf364 and 038f606.
Shall we start fresh? You remove https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/Commands.cs#L1288-L1334 and https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/Commands.cs#L1389-L1423 permanently from the codebase and then we can talk about my contributions.
But until then, _keep stealing my work_

**Comment by bartico6** [comment]
To clarify @Commaster's response, the PlayerData object will not always be non-null (players that are not logged in in non-SSC will not have this object ever initialized)
To fix, you should either initialize this object for each player that successfully spawns (as only after spawning PlayerUpdates [which cause this] are sent).  
Also this system is ridiculously complicated and thus worthy of a refactor. Something I'm not enough of a masochist to do right now, due to a ton of things on my plate related to my server alone.
  
Also, @Commaster - no need for aggression. If you don't want to contribute, just don't.

**Comment by hakusaro** [comment]
@Commaster I wanted to invite you to move discussion related to what you just said to #1510. In particular, if you can help identify specific blocks of code where you've been directly copied, that would be a significant help. In addition, I would prefer if you were to offer up whether or not you want to be _credited for your work_ or _have your work removed from the codebase_ through a rewrite in that topic.

To be clear, we want to be able to examine evidence and come to a conclusion, and we want to do it in as civil of a manner as possible.

**I understand and agree with your frustration in the similarities between the two code bases. I also humbly offer my sincerest apologies for prior treatment in this project and how we've handled your comments since then. I know that this is probably frustrating to read _now that it's 2017_, but I will personally endeavor to reach a logical conclusion regarding this, as well as de-escalate hostilities between us and you going forward.**

**Comment by QuiCM** [comment]
Now that the above drama is dealt with, we should fix this issue.

**Comment by hakusaro** [comment]
@QuiCM any way that doesn't involve what he said (backseat coding?)?

**Comment by bartico6** [comment]
I'm afraid Commaster makes a valid point - the .PlayerData objects remain uninitialized for players not logged in in nonSSC. Best bet would be to either initialize it for everyone as they spawn, or add a null-check.
