### ISSUE TITLE
tS' LinuxTcpSocket not consistent with OTAPI/TSAPI-modified TcpSocket

### ISSUE THREAD

**Issue by bartico6** [Pryaxis/TShock#1466]
The custom class in TShock called "LinuxTcpSocket" is not consistent with the TcpSocket built into the modified TerrariaServer executable that you get by compiling TShock and its deps.

The inconsistencies are mainly field accessibility, with fields in TShock's Linux version being private, and the exact same fields being public in TcpSocket

![Proof](http://i.imgur.com/InYuSrz.png)

Suggestion would be to either make LinuxTcpSocket fields public like they are in TcpSocket, or make TcpSocket fields private like they are in LinuxTcpSocket.

This is completely invalid for stock Terraria. The fields in TcpSocket are public only in TShock.

**Comment by Enerdy** [comment]
The OTAPI patcher that modifies TerrariaServer makes every private field public in order to aid development IIRC, seeing as Terraria has a lot of inconsistent field acessibility. The LinuxTcpSocket as seen in TShock may as well have been a carbon copy of the mentioned TcpSocket from a decompiled version of TerrariaServer back in the day.

With that being said, I don't see a problem with fields being made public. Unless there's any practical problem that I might've missed seeing as I'm writing this on my phone, I'd suggest a Pull Request with the suggested changes.

**Comment by bartico6** [comment]
I will send in a PR in a bit, then. Give me 1 hour tops.

**Comment by ProfessorXZ** [comment]
@bartico6 soooo what happened with the PR?

**Comment by hakusaro** [comment]
@ProfessorXZ "Give me 1 hour tops"

**Comment by bartico6** [comment]
If I say I've been busy rewriting my server from 0, will you buy it? Because I have.
also quake can't into git cloning, I needed georg to help me >.>
