### ISSUE TITLE
TShock doesn't respect -world parameter

### ISSUE THREAD

**Issue by Celant** [Pryaxis/TShock#1483]
If TShock is passed the following command-line:
`TerrariaServer.exe -worldpath C:\tshock\Worlds -world "C:\tshock\Worlds\Saveme.wld" -autocreate 1`
The expected behaviour should be the server generating "Saveme.wld" in the worlds folder.

The actual behaviour is "World.wld" "World2.wld" "World3.wld" etc being generated with each restart.

If the -autocreate parameter is removed, the server does crash with:
`System.IO.FileNotFoundException: Could not find file 'C:\tshock\Worlds\Saveme.wld'.`
This suggests the parameter is being listened to by some things and not others

My professional diagnosis, is it's borked :(

**Comment by hakusaro** [comment]
I believe, though I'm not 100% that, this has changed a lot since the original implementation. We should really just let Terraria figure this one out.

Though, now I'm curious: We do have GSPs that use these options regularly. I think some combination of world and worldpath must be working because we haven't heard an outcry from them that nothing works in the latest release.

**Comment by Celant** [comment]
@hakusaro My creation of this issue was thanks to a report from Multiplay 🙂  I've verified the bug locally

**Comment by hakusaro** [comment]
Oh, lol.

**Comment by DeathCradle** [comment]
I was experiencing this exact issue when the Main.worldName variable was not set, and similarly a problem also exists if you don't specify the world path either (this bug will increment the world file name that you specify instead of "World").

Starting with no worlds and testing both variants below after generating a world:
This generates another world: `TerrariaServer.exe -world "F:\\tshock\\Test.wld" -worldpath "F:\\tshock\\" -autocreate 1`
This loads fine: `TerrariaServer.exe -world "F:\\tshock\\Test.wld" -worldname Test -worldpath "F:\\tshock\\" -autocreate 1`

I'm thinking that when we read the -world parameter in [TSAPI](https://github.com/Pryaxis/TerrariaAPI-Server/blob/general-devel/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs#L192), we should automatically set the world name and world path if they are blank.

**Comment by DeathCradle** [comment]
@Celant Can you please test with the PR I have submitted please?
@mistzzt and myself appear to have it working now, but ideally we need a bit more testing in case i missed something.

**Comment by Celant** [comment]
@DeathCradle Had Multiplay test this fix, and the problem is fixed. Happy to close!
