### ISSUE TITLE
[Feature request] Support for region renaming

### ISSUE THREAD

**Issue by koneko-nyan** [Pryaxis/TShock#1498]
As specified in title, add /region rename \<old name\> \<new name\> to change names of regions without having to delete and redefine them.

**Comment by hakusaro** [comment]
Since you said you wanted to work on this I'm letting you take the lead for a bit.

**Comment by ProfessorXZ** [comment]
@hakusaro @koneko-nyan Imho, since the "Pull Request Wanted" label has been removed @koneko-nyan should be assigned to this issue so other people don't pick it up and someone else's work goes to waste.

I'd also like to point out that if you are going to work on this issue you should consider adding a `RegionRenamed` hook. There are a few plugins out there that store existing regions in order to perform some logic (e.g [Zaicon's DieMob](https://github.com/Zaicon/DieMob)). `RegionRenamed` would allow the developer to automatically update all references through code without requiring the end user to manually do it through database management systems.
