### ISSUE TITLE
SSC not properly ignored for users with ignore permission

### ISSUE THREAD

**Issue by Brycey92** [Pryaxis/TShock#1503]
## TShock version
4.3.24

## Steps to reproduce
1. Join the game and log in with a superadmin account
2. Get or drop stuff
3. Leave the game
4. Join the game again and log in
5. User-side player file never received inventory changes on logout, so is "reset"

Currently working on testing with non-superadmin account with ignore perm

**Comment by QuiCM** [comment]
This is by design for superadmin accounts

**Comment by Brycey92** [comment]
Why would a superadmin want to be unable to have their inventory save?

**Comment by QuiCM** [comment]
Superadmin is not intended for playing with - it is intended to act with the power of the console without needing to access the console

**Comment by macks2008** [comment]
@QuiCM 
I am in agreement with @Brycey92. Why should I have to change my group (superadmin-de-admin) or have a separate account for superadmin? Even if super admin is not meant to be played with and meant to instead be a separate or something, this still highlights an apparent bug with the SSC ignore permission. Please reopen this ticket because this does NOT seem right.

**Comment by macks2008** [comment]
side note: is there a discord for discussing this somewhere?

**Comment by Zaicon** [comment]
This is the best place to discuss issues, but you can join the tShock Discord [here](https://discordapp.com/invite/zXS2Zv).

**Comment by hakusaro** [comment]
@macks2008 superadmin was designed to be the effective "root" user. Just like root on unix, you aren't supposed to run as root, even in single user systems. If we were to change the behavior of ignoressc, the root user would have to dump all items upon entering the server even just to do basic configuration. It stands to reason that a new user joining the server for the first time who promotes themselves to temporary superadmin would prefer to not have to comply with the server's SSC requirements in initial setup.

Because it's the initial setup role and for only the highest level of changes, we aren't considering adding additional logic to handle how the superadmin permission scheme works for just one feature.

**Comment by macks2008** [comment]
@hakusaro my issue is not that a super admin can ignore SSC. My issue is that if it reads my local player data when I join (rather than the server-side character data), why shouldn't it write back to that when I leave? It's deleting items, and I don't understand why that's a 'good thing' or even a 'necessary evil'

**Comment by hakusaro** [comment]
We do currently have two commands that might accomplish what you're looking for?

- /uploadssc
- /savessc

**Comment by macks2008** [comment]
@hakusaro thanks, that does help a little.. At least now I can disconnect without losing stuff until I figure this out. I still want to know why this isn't an automatic thing though. If you read from a file, then improve upon it (unless my superadmin dies as a medium core or otherwise drops wanted items, it's an improvement), why not (automatically, in this case) save back to that file?
also, I tried negating the ignore permission (as described [here](https://tshock.readme.io/docs/server-side-character-config)), but instead of having all permissions except the ignore permission, I ended up with NO permissions and had to fix it from the server console. Did I do something wrong?
here's the sequence of commands I ran (although the new group had a different name)
/group add noignoreSSC
/group addperm <group name> !tshock.ignore.ssc
/group parent noignoreSSC superadmin (this might be backwards or I may have run it backwards, in which case that would explain it. Let's assume I had it correct though)
/user group <myusername> noignoreSSC

**Comment by macks2008** [comment]
@hakusaro I tried using that command but my inventory still didn't save, as I still ended up with the outdated inventory next time I joined after using /savessc. Am I missing something?

**Comment by hakusaro** [comment]
To be quite honest, the problem is that "ignore ssc" probably doesn't even enable SSC on the client. Since SSC was basically implemented by one person, and that one person was the reason why SSC exists in Terraria in the first place, to call it undocumented would be an understatement.

If you note that [this code block](https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/TSPlayer.cs#L449) both ignores saving and also returns true, we could almost call this unintentional functionality. SSC is designed with the premise of being a cheat prevention tool, which is why it's in the same category as hack detection and all that other jazz. The implication is that if you turn off ssc for a player or group, you're intentionally not saving their character data to the server. You could argue that without the system designer chiming in, we don't really have any way of knowing the true intention of that permission. We could change it, in theory. That's also why /savessc doesn't work on the super admin (that permission is granted, which stops us from saving data).

Lastly, the superadmin group is defined in code here: https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/Group.cs#L326

As you can see, we forcibly override the has permission check to just return true for all permissions. Modifying it directly is impossible.

**Comment by QuiCM** [comment]
For the record: when a server is in SSC mode, player data is NEVER written back to the client's player file.
It is simply saved on the server. In the superadmin accounts case, the superadmin simply ignores attempts to modify its inventory.
We have no intention of changing this, but that's not to say a PR can't be made for it

Also note that SSC applies to the whole server rather than to individual users on the server - you cannot selectively apply SSC (without introducing a race condition)

**Comment by hakusaro** [comment]
I'd like to add that that's more of a technical detail about the Terraria protocol. The packet associated with world information is what determines if the Terraria client is running in "allow the server to do anything mode."

**Comment by macks2008** [comment]
Thanks for explaining. I think I understand. Sounds like it's sort of a shit situation because of the beyond-undocumented nature of the SSC system. Unless someone is willing to volunteer a lot of time to figure it out (which would presumably involve a lot of trial and error, due to said undocumented issue), you can't do anything?

**Comment by bartico6** [comment]
I could mess with it someday provided there aren't big changes to how it works pending in 1.3.6 or TShock5 or next release.

You also CAN selectively apply SSC but not out of the box, you need to do some wizardry with an external plugin.

**Comment by macks2008** [comment]
if you can't fix it, can you at least try to help me figure out what I did wrong in that sequence of commands I listed above?   I'm pretty sure I didn't mix up the "/group parent" command as I initially suspected, so what went wrong?

**Comment by macks2008** [comment]
I was trying to apply SSC to myself by changing myself to a group inheriting from superad but negating the ignorescc permission

**Comment by bartico6** [comment]
SuperAdminGroup is overridden to ALWAYS have ALL permissions regardless of parenting etc (see https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/Group.cs#L355). You can't make it not have permissions. That's why you should create your own admin group.

**Comment by macks2008** [comment]
oh. so the page I referenced on this repository's wiki needs to be fixed? Because it doesn't seem to be accounting for that. [Guide Dang It!](http://tvtropes.org/pmwiki/pmwiki.php/Main/GuideDangIt)

**Comment by macks2008** [comment]
wait, it's not on this repository. Strike that part. It's on the website's wiki

**Comment by macks2008** [comment]
I guess I should use (directly or as a parent of a new group "Owner") one of the builtin admin groups. What's the effective difference between superadmin (and ignoring superadmin's immutable nature) and trustedadmin? That is, what permissions, if any, are not included in trustedadmin? I assume tshock.ignore.ssc is excluded, but are there any others?

**Comment by Zaicon** [comment]
Unfortunately, the superadmin group itself technically doesn't have any permissions (since it overrides permission checking for that group), so inheriting from the superadmin group doesn't inherit anything (which is why your attempt failed).

There are quite a few things missing from trustedadmin (specifically compared to superadmin). You can achieve what you want by creating a new group and adding the permissions "*" and "!tshock.ignore.ssc", though it's worth the time to manually create groups and assign only the permissions it needs.

**Comment by Enerdy** [comment]
Yeah, its as Zaicon said. To clarify, permissions accept wildcards as "anything past that point", so if you wanted to give all core tshock permissions to a group, for example, you could give them `tshock.*`. This means that if you give a group the `*` permission, you are effectively replicating root access to every existing and future command, and you can then negate the permissions you don't want by appending `!` before said permission.
On 6 Nov 2017, at 13:01, Zaicon <notifications@github.com<mailto:notifications@github.com>> wrote:

Unfortunately, the superadmin group itself technically doesn't have any permissions (since it overrides permission checking for that group), so inheriting from the superadmin group doesn't inherit anything (which is why your attempt failed).

There are quite a few things missing from trustedadmin (specifically compared to superadmin). You can achieve what you want by creating a new group and adding the permissions "*" and "!tshock.ignore.ssc", though it's worth the time to manually create groups and assign only the permissions it needs.

**Comment by macks2008** [comment]
oh, we have wildcards? I know all about those from using things like bukkit and [SpongePowered](https://www.spongepowered.org/)[\[1\]](https://github.com/SpongePowered)(specifically SpongeForge) to host Minecraft servers. That makes things really simple for me. Thanks!

**Comment by macks2008** [comment]
While we're on the topic of server permission architecture (the thought of Minecraft reminded me of this): will there ever be a way to assign multiple groups as parents of a different group (or user)? To my knowledge, most plugin permission managers for Minecraft servers offer such functionality, and it comes in under certain circumstances. Examples:
\#1: what if I want to group permissions for a specific plugin/feature and then give certain people permission (or advanced permission) to manage certain plugins/features. It may seem redundant from your perspective, but I've used it to excellent effect on a Minecraft server. 
\#2: what if I have a VIP group that I want completely separate from the ADMIN (or at least from the MODERATOR) groups? Just because I trust them to moderate or something doesn't mean they are supporting the server on patreon, etc., and I may want to be able to assign VIP permissions to one person with MODERATOR but not another

**Comment by bartico6** [comment]
Since the OnPermission hook can now allow you to both grant and deny the permission, you should expect a PermissionsEx'esque kinda plugin in the future. I'll think of writing one myself.

**Comment by Enerdy** [comment]
We may be removing group parenting entirely in favor of multiple user account groups when we rebuild our system in TShock5. It's far more flexible and avoids recursive parenting hell. This should allow you to do all of these easily, by creating a group with specific permissions for a plugin and then assigning users to that group at will without a hard limit of one group per user.

**Comment by Enerdy** [comment]
In the meantime, major changes to the permission system will most likely be welcome through plugins that abuse said hook @bartico6.

**Comment by bartico6** [comment]
Parenting should stay given it allows you to tier groups (moderator inherits juniormod, admin inherits mod) et cetera.

**Comment by hakusaro** [comment]
I think this issue has reached its life expectancy. If there are any more unrelated tangents that people want to discuss, feel free to continue on discord or in the appropriate other issue. The only code problem I see here is now covered by #1506. Once /savessc works in superadmin context, I'm happy.

**Comment by macks2008** [comment]
@Zaicon @hakusaro before we perform internment on this issue, I do have one last request: a discord link that doesn't yield the "invalid or expired" error when I try to use it... can't really discuss on discord without being in the same channel/guild
the sooner you can reply, the better, as I'm actively trying to debug my permissions and I'm not sure which perm "node"/string I need for something

**Comment by Zaicon** [comment]
https://discord.gg/cnbmKVn

**Comment by hakusaro** [comment]
@macks2008 the Discord link on the readme works, so I'm unsure which one you followed/couldn't find

**Comment by bartico6** [comment]
The link gives a "invalid or expired" error when one of the following criteria is met:  
1. Link is actually dead  
2. Server is removed.  
3. *You are banned from this server*  
Since the server works for everyone and the link is okay, I'm assuming you, or your IP address (not necessarily you) are banned.  
That said, sorry for the off-topic comment. I hope you get onto the server without issues.

**Comment by hakusaro** [comment]
Just wanted to confirm that both Zaicon and my instant invite links are both valid and working according to the Discord invite list.

This is the full ban list:

![screen shot 2017-11-09 at 08 14 13](https://user-images.githubusercontent.com/532647/32612649-073268de-c526-11e7-9c36-e50e925b7bbd.png)

**Comment by macks2008** [comment]
I was able to get on the discord just fine with the second link Zaicon posted. The first one gave me the invalid error. Maybe my IP address changed or something, but in any case, I'm in

**Comment by Brycey92** [comment]
Please discuss Discord invite issues in another issue report so I don't get notified every time something irrelevant to my issue is posted. Thanks!

**Comment by hakusaro** [comment]
![screen shot 2017-11-16 at 09 23 54](https://user-images.githubusercontent.com/532647/32902546-e328d5ba-caaf-11e7-8091-cb1ecbb83e02.png)
