### ISSUE TITLE
TShock Server Join via Steam Support

### ISSUE THREAD

**Issue by JackNerdcore** [Pryaxis/TShock#1504]
## TShock version 4.3.24

If I start a TShock Server and tried to forward it through Steam (Join via Steam function) it doesn't respond to Steam, so my friend doesn't receive an invitation.

**Comment by hakusaro** [comment]
Yep, not possible unless you start TShock through Steam. I'll save you the Googling though and tell you that it's 100% impossible for this to ever work in the current way that Terraria MP is designed. Steam invites will only work from client hosted servers.

**Comment by sanscriptum** [comment]
But vanilla terraria server has ``-steam`` key which allows connections via steam for friends. Is it possible to add that to tshock as well?

Asking because that's the only option for people who cannot forward their ports (i.e. they're closed from ISP side) host the game and be able to receive connections without using stuff like hamachi, which is laggy and not reliable.

**Comment by hakusaro** [comment]
We (TShock) can’t get the required steam authentication ticket unless Steam launches us and Steamworks initializes properly.

**Comment by Bonkorn** [comment]
https://github.com/csnxs/Terraria/tree/master/TerrariaServer/Terraria/Social
? Sorry for nercro but i really want IP not to leak and allow steam friends only.

**Comment by hakusaro** [comment]
Just for the record, you aren't going to be able to stop IP leakage at all because Steam is just used as a session establishment system, not a forward proxy for all traffic. Anyone who connects to your server will still be sending packets to your IP.
