### ISSUE TITLE
[Security] Tshock stats collection security concerns. Related to #1446.

### ISSUE THREAD

**Issue by pgwipeout** [Pryaxis/TShock#1631]
Tshock Stats Collector is making round robin connections to various AWS buckets and using GET requests to post statistical data on the server. 
The following security concerns currently apply to the current system:
- Connections are made over HTTP, with all data in clear text.
- Data posted contains the current port the server is running on.
- Use of HTTP means there can be no client verification of the identity of the server.
- Exposure of the listening port in the GET request, combined with the IP address of the server broadcasts the server identity to malicious actors.
- The Stats Collector is embedded in a closed source binary included in the open source code, making transparency and auditing difficult.
- The Stats Collector has a disable flag, --stats-optout, but it is not documented in the configuration documentation.

This servers are currently responding with the following:
{"extra":"Ichigo is the best.","also":"The TShock stats server is offline intentionally."}

The server's HTTPS certificate is invalid, due to being assigned to *.bikelanesolutions.com

In addition, the following concerns were raised in Issue ticket #1446:
- Lack of notification of the existence of the Stats Collector.
- Lack of transparency.

It is mentioned at the close of ticket #1446 that the Stats Collector was killed on May 21, however the Stats Collector is still connecting to servers and posting data.

As such, the following changes are recommended:
- Move the Stats Collector to the Tshock open source code base.
- Convert the Stats Collector to use only HTTPS connections to prevent Man in the Middle attacks and to ensure data integrity.
- Ensure the Stats Collector performs certificate verification of the receiving server to prevent spoofing attacks.
- Make the server explicitly declare the existence of the Stats Collector.
- Make the Stats Collector opt-in vice opt-out.

Confirmed valid as of TShock version: 4.3.25 on August 15th, 2018.

**Comment by hakusaro** [comment]
Hi, thanks for your thoughtful issue. I've been very busy and this is a very low priority thing, so I've only now been able to reply to your thoughts and provide some insight.

The stat tracking system was removed and the current stat tracking server used to be open source, but it's pretty useless to publish the source. It's just a Sinatra app that returns that JSON payload to all clients and responds back. If we were to simply take it offline, it would cause every existing TShock server to error, which is a problem. No data is stored by the stat tracking system.

> The Stats Collector is embedded in a closed source binary included in the open source code, making transparency and auditing difficult.

I'm afraid I don't know what you mean by this. The stats collector is open source, not a closed source binary. You can see the source here: https://github.com/Pryaxis/TShock/blob/master/TShockAPI/StatTracker.cs

> The server's HTTPS certificate is invalid, due to being assigned to *.bikelanesolutions.com

I don't really don't know what you mean by this. I assume you're referring to the TLS cert on tshock.co. We use CloudFlare for a variety of reasons, which means that a CloudFlare SNI certificate for a variety of domains also includes us -- but does not exclude other people. This is standard in our configuration.

> Convert the Stats Collector to use only HTTPS connections to prevent Man in the Middle attacks and to ensure data integrity.

The stat tracker simply displays an OK or a not okay if it fails. The information it uploads is basic system information, none of which would be helpful for any real world attacker. If someone os MITMing your connection, you have a much larger problem than your TShock server's stat update mechanism. While not a perfect analogy, you should read over [It rather involved being on the other side of this airtight hatchway](https://blogs.msdn.microsoft.com/oldnewthing/20060508-22/?p=31283) as an exercise -- because in practice, MITMing a TShock server's stat tracking system could only reveal the most mundane data possible to an attacker. If they're already doing this, they can exfiltrate much more damaging information from other services on the system.

> The Stats Collector has a disable flag, --stats-optout, but it is not documented in the configuration documentation.

This is a really good point, and it needs to be documented.

> Tshock Stats Collector is making round robin connections to various AWS buckets and using GET requests to post statistical data on the server.

To be more specific, it's making GETs to a Heroku app.

----

Since this issue is mostly filled with things that aren't useful for us (we've removed the stat tracker, and all of the other code changes would require another release, which will include the stat tracker removal), I'm going to close this issue and prioritize a master release that will remove the stat tracker from stable builds. It will, of course, require users to upgrade their server and get the changes, so we have to keep the old system running to make servers happy in the interim period.
