### ISSUE TITLE
[Suggestion] Expand Tshock server update mechanism.

### ISSUE THREAD

**Issue by pgwipeout** [Pryaxis/TShock#1632]
The Tshock server makes connections to an unsecure update server every thirty minutes to check for updates.
This raises the following security concerns:
- Connections are made over HTTP, with all data in clear text.
- Use of HTTP means there can be no client verification of the identity of the server.

In addition, there is no mechanism to disable the auto update function.

As such, the following changes are recommended:
- Convert the update function to use HTTPS exclusively.
- Ensure the update function is performing certificate verification to ensure the validity of the server.
- Add configuration items to change the update check frequency and to disable it altogether. 

Confirmed valid as of TShock version: 4.3.25 on August 15th, 2018.

**Comment by hakusaro** [comment]
> Add configuration items to change the update check frequency and to disable it altogether.

As a design choice, we don't intend to do this. Sorry. TShock has enough options in its config system, and adding another that disables the update check is just going to make more work for us in the long term.

The reason why the update checker operates over HTTP instead of TLS is because of a vestigial mono problem. Back in the Mono 3 era, both the stat tracker and the update checker were written to use non-encrypted HTTP because Mono didn't ship with an HTTP Client that had any trusted root certificate authorities. This meant that any update checker or stat collection system wouldn't have worked out of the box -- and we didn't want to run the root certificate update and trust arbitrary root authorities on end user systems.

There is literally no problem if this is MITM'd. You have bigger problems if someone is impersonating arbitrary servers on your connection, because they can do a lot more damage than simply faking TShock update checker replies.

I'm going to open an issue to move the update tracker to use TLS, but this isn't high priority.
