### ISSUE TITLE
An unhandled exception has occured in TSAPI

### ISSUE THREAD

**Issue by pcgamerz** [Pryaxis/TShock#1662]
[crash_131945420669075580.zip](https://github.com/Pryaxis/TShock/files/2898637/crash_131945420669075580.zip)

Why is my server keep shutting down every once in a while? I have checked the crash report and the following seems to be the issue,

[02/13/19 09:34:26] [Server API] Error: ===================================================================================
[02/13/19 09:34:26] [Server API] Error: An unhandled exception has occured in TSAPI, and a crash report will be generated
[02/13/19 09:34:26] [Server API] Error: Generating a crash report, please wait...
[02/13/19 09:34:27] [Server API] Error: Crash report saved at crash_131945420669075580.zip
[02/13/19 09:34:27] [Server API] Error: Please upload the crash file and report it at http://tshock.co/
[02/13/19 09:34:27] [Server API] Error: The process will terminate.
[02/13/19 09:34:27] [Server API] Error: ===================================================================================

"exception": {
"message": "The socket is not connected",
"type": "SocketException",
"trace": " at System.Net.Sockets.Socket.get_RemoteEndPoint () [0x00035] in <102ddc49e9884872921866bb2bd1bab6>:0 \n at HttpServer.HttpListener.OnSocketAccepted (System.IAsyncResult ar) [0x000db] in <0bb72d76034a4517b7a1f3b62e0cc3e7>:0 \n at System.Net.Sockets.SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state) [0x0000b] in <102ddc49e9884872921866bb2bd1bab6>:0 \n at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <7c6726ddba2042189622013443252667>:0 \n at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <7c6726ddba2042189622013443252667>:0 \n at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <7c6726ddba2042189622013443252667>:0 ",
"inner": null

I have a 32gb dedicated private game server it runs Centos 7, and I use Mono to run the tShock server.
When I restart the server it never uploads the latest map I have to upload the latest map myself. I anyone can provide a solution to both how to keep my server from shutting down and how to automatically upload the latest map I would really, really appreciate it!

"os": {
"x64": "yes",
"x64Process": "yes",
"Platform": "Unix",
"Version": "Unix 4.9.144.6"
},
"hardware": {
"CPUs": 8,
"CPUID": null
},
"server": {
"Players": 0,
"MaxPlayers": 255,
"WorldName": "Terraria",
"WorldFile": "/root/.local/share/Terraria/Worlds/Terraria.wld",
"Time": 14008.0
},
"process": {
"curRelease": 194,
"TSAPIVersion": "1.3.5.3",
"Uptime": "3.10:18:56.1144870",

**Comment by tylerjwatson** [comment]
Please keep issues to one specific topic.  Asking for as much as possible in one sentence isn't enabling us to help you in the best way possible.  Also, please note that GitHub issues are a repository for software issues only, please use the forums at tshock.co for support on running a server.

The solution to the crashes should be solved by disabling REST, or using Windows to run the Terraria server.

It's also strongly advised against running any multiplayer servers as root.  Doing so is a security risk and we can't be held responsible if your server gets compromised.

Cheers

**Comment by pcgamerz** [comment]
Hello,

Thank you for the quick reply and your suggestions.  I am still left hungry
with curiosity as to how you came up with the two solutions to this
problem.  Is there maybe a link you can please provide where I can read
more on this or maybe please at least explain why the problem happens in
the first place.  Thank you in advance.

**Comment by tylerjwatson** [comment]
Sure.

## Number 1 
Looking at the stack trace of the crash, I can see that the callsite in the second last frame is pointing to `HttpServer.HttpListener.OnSocketAccepted`.  Having being involed in this project for quite a long time I can tell you that `HttpServer` is a .NET assembly that implements a very basic (and buggy) HTTP server.  The HTTP server is used for the REST server in TShock.

Unless you _need_ REST support, it's another thing that can potentially destroy stability, and if you don't need it turn it off.

Now, it shouldn't crash even with it on and I can't tell you _exactly why_ it crashed, but what I can tell you is from the endless dealings with the pain and frustration with mono:  The way mono implements sockets is quite different to Windows because of the vastly different kernel infrastructure between them.  `Socket.RemoteEndPoint getter` shouldn't crash, but the runtime differences between the two platforms can, and certainly does bring out these quirks.  On Linux this probably uses a syscall which is why the program hard-crashes when the kernel tells it to go away.  The `HttpServer` assembly is old, and has very poor handling of error cases.

My speculation on why it _actually_ happens:  More than likely half-open TCP sockets.  Being on the internet, you're subjected to all sorts of scans from spiders and bots, I wouldn't be surprised if it's just the mishandling of a half-open TCP socket by some bot in China.  Disabling REST shuts that hole off.

Here's a list of things that annoy me with running Terraria that has had me try to delve into the Mono sourcecode on behalf of TShock over the years, in no particular order:

1.  Mono's threadpool doesn't spawn new threadpool threads when it's exhausted fast enough, causing TShock to freeze with 100% CPU usage soon after load on some systems
2. Mono's async socket implementation causes races and can lead to even more performance loss, leading TShock to disable async sockets altogether on Mono for a good while
3. Mono's JIT ignores the x86 flag in the windows PE header (exe) file and runs the binary in 64-bit mode anyway, leading to 50% more memory usage in Linux as compared to Windows, and some benign race conditions
4. Mono's Rand implementation can be quite slow leading to gametick slowdowns both in the client and server on Windows

## Number 2

TShock is a binary modification to the native Terraria server, and the reality is that Re-Logic designed the program using .NET code on Windows to run on Windows machines; they assumed the Windows .NET garbage collector, and a complete and working Windows environment.  TShock can do very little when it comes to extra support on Linux where we don't control the base code and have no access to modify Re-Logic's game client.  While there are Linux ports, if you want to run with the same consistency that the developers intended, it simply makes the most sense to run it on the same platform as the developers, and all the support.  _Any_ variables you introduce in your environment can potentially come back to bite you.

As a team member, we've simply had too many issues on Linux to not rule it as an automatic problem.

Cheers

**Comment by pcgamerz** [comment]
WOW!  Thank you so much for the very detail explanation I truly appreciate this.
I will switch my server back to Windows 2016 Standard Server, but I need REST enable because I use it for the two voting plugins which require REST to work.  Once again, a big THANK YOU!

**Comment by bartico6** [comment]
Side note, if you're using REST to accept vote reward bots, do yourself a favor and ban connections to your REST port from any IP that isn't the website's backend. This should also help you.

**Comment by sr229** [comment]
Also another side note, `iptables` and `ufw` also helps, blocking access using CloudFlare can also help

**Comment by pcgamerz** [comment]
Hi [Tyler](https://github.com/tylerjwatson),
Just wanted to provide a feedback.  It has been over 3 weeks, since I switched back to a Windows Server and my Terraria server has been running everyday non stop without ever crashed again.  Thank you so much for your help!
