### ISSUE TITLE
/bloodmoon is now caught by the client and can't be used as a command

### ISSUE THREAD

**Issue by QuiCM** [Pryaxis/TShock#1765]
/bloodmoon triggers an emote now, instead of being sent to the server for processing. 
Need to check if the text is still sent to the server and can be handled appropriately, or if we now have a bunch of reserved commands we can't touch

**Comment by hakusaro** [comment]
Fixed in the most ghetto way possible by renaming this to `/tbloodmoon`. I think long term we just need to change the command prefix to `.` or something.

**Comment by moisterrific** [comment]
What about revamping how event commands are done? Instead of having several commands for different events, have one `/event` command with parameters like blood moon, party, etc.

Kinda like how they’re organized according to the wiki https://terraria.gamepedia.com/Events

To stop the command I guess you’d have to type `/event <name>` again, or `/event stop` to cancel all active events

**Comment by QuiCM** [comment]
> 
> 
> What about revamping how event commands are done? Instead of having several commands for different events, have one `/event` command with parameters like blood moon, party, etc.
> 
> Kinda like how they’re organized according to the wiki https://terraria.gamepedia.com/Events
> 
> To stop the command I guess you’d have to type `/event <name>` again, or `/event stop` to cancel all active events

I like this idea

**Comment by hakusaro** [comment]
It’s a good idea long term. Low priority short term imho. Good first time project for someone to work on.

Lucas Nicodemus
http://keybase.io/xn

**Comment by nikitamatrosoff** [comment]
It's better to rename it to `/blood`, don't you think? `/tbloodmoon` looks weird.

**Comment by QuiCM** [comment]
Resolved with the addition of the `worldevent` command
