### ISSUE TITLE
Only super admin can place Mannequins 

### ISSUE THREAD

**Issue by mikedmor** [Pryaxis/TShock#1815]
* TShock version: 4.4 Pre 2

#### Reproduction steps (if applicable)?

1. Craft Mannequin as group default user
2. Upon placing the Mannequin it immediately destroys itself without dropping an item
3. Log off of default user and log into SuperAdmin
4. Craft Mannequin and Place it without any problems.

I couldnt find any permissions that would solve this and thought it may be a bug. Please let me know if there is something i missed. Attached is a picture of the current permissions for group "Default"

![image](https://user-images.githubusercontent.com/1064037/82474225-b922e600-9a98-11ea-82fc-23a1335c71da.png)

#### Any stack traces or error messages (if known)?

```
No known errors in the log.
```

**Comment by Marcus101RR** [comment]
The issue is not with SuperAdmin, its all perms you go so therefor the `tshock.ignore.sendtilesquare` is invoked. It resolves this issue, temporary. The oddball here is that From old TShock when it was handled by the data handler without returning `return` to the new tshock which now the Bouncer handles, sends `return` and `args.Handled`, the issue being `return`. Not sure how this can be fixed as apparently it has security risks? But I removed it for now to allow people to stop complaining.

**Comment by Patrikkk** [comment]
#1795 #1774 Are also related to the same issue, `tshock.ignore.sendtilesquare`
Have been tested.

**Comment by hakusaro** [comment]
This should be fixed in the next pre-release.
