### ISSUE TITLE
Unable to access chests or world after death

### ISSUE THREAD

**Issue by Tibbind** [Pryaxis/TShock#1820]
* TShock version:4.4.0 226 pre3 
* TShock build number (if known): maybe above

#### Reproduction steps (if applicable)?

1. die
2. try to access chests
3. can't chop down trees or access chests, nothing happens

#### Any stack traces or error messages (if known)? na

```
no error message
```

#### Any log messages from files that end in `.log` or `.txt`? no

 happens after playing, whether it be 1 minute or a couple hours

#### What plugins and what versions of those plugins are you running?
no plugins

**Comment by Bawnorton** [comment]
Same issue in Pre 4, all members of my server are experiencing this.

1. Player 1 dies
2. Player 1 respawns and appears to player 2 as running in one direction, swinging constantly or just standing
3. Player 1 on client-side is doing their own thing but they cannot interact with anything, player 1 cannot open chests and breaking blocks does not cause the tile to drop, all the while appearing to player 2 as stationary or running in one direction or swinging.
4. Player 1 can attack and kill things client-side but they reappear shortly after as if they did nothing to them.

**Comment by Tibbind** [comment]
Yes, I updated to pre4 and am still having same issue, as well as player
desync. Hopefully it's fixed soon

**Comment by Zerosk83** [comment]
I'm also seeing this issue. Saw it in all "Pre" versions so far. It doesn't seem to happen every time I die I die though. I don't think it happens to all players either. I seem to be especially affected, some of my users have said once in a while and others have said it's never happened. 

When I respawn I'm always way out in the middle of nowhere to the left or right of spawn. It's like I respawn and then run to one side for the duration that I remain connected in "ghost" mode. 

Running with Server Side Characters on, I'm connecting over LAN to another machine and all 5 other players connect over the internet. 
Still on Pre hardmode.
I can't recall if it happens when I'm the only one though. Might be a fluke or might be related to others being on the server. I'll update if I get a chance to test this.

**Comment by dly2424** [comment]
New release hasnt come out yet, but is supposedly fixed when it is.

**Comment by QuiCM** [comment]
Closing - tracked under #1779
