### ISSUE TITLE
Godmode does not work with daytime Empress of Light

### ISSUE THREAD

**Issue by gamerpiss** [Pryaxis/TShock#1899]
Not sure if this has been reported already, but Empress of Light instantly killed me while in godmode. Now that the new Journey mode has it's own godmode (no damage and no mana usage), maybe update Tschock's godmode to match Journey mode's?

**Comment by hakusaro** [comment]
There's not enough information in this report, @gamerpiss, including versions of TShock, logs, or screenshots for us to be able to take any information on this. I'm really sorry again @gamerpiss, but we won't be able to investigate this until we're satisfied with all of the other issues that we have known reproduction steps on.

Thank you so much for reporting this -- if you get any more information, please let us know, @gamerpiss!

**Comment by hakusaro** [comment]
The reason why this happens is because journey mode and TShock god mode are implemented differently. Journey mode god mode is the client ignoring damage. The terraria system for damage and death is essentially that the client decides to accept damage or not. When we give you god mode, we are really just healing you up from near death. It’s kind of like Buddha mode in other games where you can recover from 1hp. That means an instant kill can still kill you.

The current question is whether or not we can temporarily turn a player into a journey mode player or not, and if we can temporarily apply the god mode changes. We currently don’t know if it’s fully possible to do that.
