### ISSUE TITLE
Add /spawn command perms to owner

### ISSUE THREAD

**Issue by moisterrific** [Pryaxis/TShock#1932]
How come owner group does not have this permission? Is there a specific reason or was that an oversight? 

I want to get some input from TShock devs before making a pull request.

**Comment by hakusaro** [comment]
There's no good reason, ya. The initial groups are pretty restrictive. Open to any suggestions.

**Comment by moisterrific** [comment]
Maybe it’s time for a revision on which groups should get certain permissions? 

At the very least it doesn’t make sense you’d need superadmin to use a command that teleports you to the world spawn lol

**Comment by hakusaro** [comment]
I mean, again, I'm hope to any suggestions for this. The reason why `Owner` is locked down is because `/su` can escalate you to superadmin and `/sudo` lets you run any command. Any reasonable set of defaults we want to move to would be an improvement. Heck basically all permissions could be given to lower groups than Owner and I'd be happy.

Heck we could make multiple different default groups. `FancyOwner` and `BasicOwner` and `ClassicOwner` with different sets. No problems going wild on any of them.

**Comment by hakusaro** [comment]
@moisterrific you finished/solved this one, so I'm closing this.
