### ISSUE TITLE
Ropes are still buggy

### ISSUE THREAD

**Issue by QuiCM** [Pryaxis/TShock#1980]
Ropes disappear when places. Rope coils work ok

**Comment by MikeAnuta** [comment]
I too was having this issue. Seems to be in Bouncer.

**Comment by hakusaro** [comment]
Related discussion: https://github.com/Pryaxis/TShock/discussions/1976#discussioncomment-21515

**Comment by zaneshaw** [comment]
Only shows for a split second on client side. No one else hear or sees it.

**Comment by zaneshaw** [comment]
After throwing a rope coil, you can place normal ropes under any of the ropes and it works.

**Comment by Rodrogamby** [comment]
Ropes are still buggy as of Pre-release 11, I tried what you said but it didn't work :/ @squidee100

**Comment by zaneshaw** [comment]
@Rodrogamby It seems it's kind of random from what I know. After placing a new coil it usually works than stops working again. [Proof (May be a a bit fast)](https://imgur.com/a/veDHhhJ)

**Comment by MikeAnuta** [comment]
The bug is in bouncer. I have not had time to figure out why the if
statement is throwing a fit but that is where I think it is.

**Comment by DMahalko** [comment]
I am not a real programmer, I don't use git, so I can't do anything about this, but so anyway I'll try to prod the real programmers along.

Is there some reason the rope placetile isinrange handler does not have a console debug log like pretty much everything else does?

https://github.com/Pryaxis/TShock/blob/general-devel/TShockAPI/Bouncer.cs#L470

**Comment by HairyMilkshakes** [comment]
So did they give up on this issue? It's still present as of the latest release?

**Comment by Rodrogamby** [comment]
> So did they give up on this issue? It's still present as of the latest release?

Yes, It’s still present.

**Comment by hakusaro** [comment]
@Rodrogamby @HairyMilkshakes as I'm sure you both are very well aware: this is a volunteer project by volunteers. Due to some external factors (from the ongoing crisis in the world to internal issues with Re-Logic), we've been busy with other things. When we have time we will certainly work on it.

> Is there some reason the rope placetile isinrange handler does not have a console debug log like pretty much everything else does?

@DMahalko `args.Handled = false;` and then a `return;` means that the event is _explicitly accepted_, which means that the event is propagated back to the server. The debug log output is specifically used to diagnose adverse rejections of messages, not acceptance of messages. In other words: that is certainly not the reason why the problem would be happening.

**Comment by hakusaro** [comment]
This issue has been thumbs up'd zero times. Please thumbs-up this issue if you'd like to prioritize it more. This helps us prioritize -- we do look at issues in sort-by-thumbs-up order.

![Screen Shot 0002-06-10 at 19 17 23 1](https://user-images.githubusercontent.com/532647/84337683-09004480-ab4f-11ea-9440-76dbf096475a.png)

**Comment by mackereldev** [comment]
Placing a player sensor doesn't work either, it just eats up the item. I'd assume this applies to the other sensors too but I haven't looked into it.

**Comment by HairyMilkshakes** [comment]
all good. thx for the clarification.
