### ISSUE TITLE
Bloodmoon fishing still bugged. 1.4.0.5

### ISSUE THREAD

**Issue by vrdiy** [Pryaxis/TShock#2011]
1.4.0.5
Bloodmoon fishing is broken, casts that would usually reel an enemy don't spawn anything.

**Comment by HamaIndustries** [comment]
This is not 100% consistent, it's working now on my server whereas it didn't work last time.

**Comment by Serverfrog** [comment]
Can Confirm that it can be not working. In my case it didn't. Had a Sonar Potion, 5 Times the Mermaid and 4 Times Eye Fish on the Hook. Successfull fished. No Spawn

**Comment by QuiCM** [comment]
Can i confirm you're all using pre11?

**Comment by Serverfrog** [comment]
I use it, just started Terraria Again 3 Days Ago and downloaded then the Latest (Pre-)Release for 1.4

**Comment by mpql** [comment]
I'm using Pre11, and we've had no issues with Bloodmoon fishing spawns on my server. I want to say they've been consistently working since we started this recent run, which was on Pre6, across both normal and hardmode. I don't know what the triggering factor would be.

It's also worth mentioning we were just fishing normally, poles and bait. No sonar potions, no extra gear.

**Comment by Serverfrog** [comment]
I used Sonar Potion, Fishing Potion and the "Sitting Duck's Fishing Pole". Fishin inside a Corrupted Lake.

The Bobber was reeled in, without anything i on it. The Sonar Potion was showing that the Mobs had bitten on.

This can't be a Problem because we loaded this map after it was generated on a Singeplayer 1.4.0.5 Map ?

**Comment by Patrikkk** [comment]
I'll try to replicate it with those circumstances, thank you for the info!
Can you please enable debug display in your tshock config? 
And try fishing the same way and look got OnFishOutNpc. This would be very helpful to identify the problem

**Comment by re-blank** [comment]
Hi, I tested tried to test this issue with various fishing rods. 

I fished in the ocean during a blood moon with Master Bait, Sonar Potions, and High Test Fishing Line. This was Pre-Hardmode, so I was fishing Zombie Merman and Wandering Eye Fish. This was on the server's owner account, if that makes a difference.

The new 1.4 fishing rods (Chum Caster, Scarab Fishing Rod) consistently failed to fish blood moon enemies, but could fish regular fish. The server shows the debug message:
`Debug: Bouncer / OnFishOutNPC rejected for not finding active bobber projectile! - From <playername>`
Interestingly, I also found that the Fiberglass Fishing Pole also failed with the same message a couple of times, but worked every other time. The times that it failed were shortly followed by the server autosave, which might have something to do with it in this case.

**Comment by Patrikkk** [comment]
Thank you for the detailed info. 
I've set up the same environment to do the testing in the latest shock version.
Bloodmoon set.
Master Bait, Sonar Potion, High Test Fishing Line used/equipped.
Using Chum Caster, Scarab Fishing Rod, Fiberglass Fishing Pole.
The user account is owner.
I've consistently succeeded at fishing out the Zombie Merman and Wandering Eye Fish NPC.
This was my setup. (ignore the crimson monsters, they came to harass me)
![](https://puu.sh/FVUdj/28a232a73e.png)

**Comment by QuiCM** [comment]
Could anyone let me know if this issue is still occurring in latest prerelease?
Thanks :)
