### ISSUE TITLE
Torch God's Favor Not Saved to Server Side Characters

### ISSUE THREAD

**Issue by MachinusRhapsody** [Pryaxis/TShock#2031]
* TShock version: 4.4.0 pre-release 11
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Set up TShock 4.4.0 pr 11 with server side character saving.
2. Log in as any character and complete Torch God's Favor event.
3. Use Torch God's Favor item.
4. Note that Torch God's Favor now applies to character in menu and toggle/ability functions as expected.
5. Log out.
6. Log back in using the same character.
7. Note Torch God's Favor no longer applies to the character. Ability is missing from the menu. Item must be re-obtained and used again. Ability lost when logged out/logged back in.

#### Any stack traces or error messages (if known)?

There's no error message. I'm guessing the database isn't updated to handle a new character flag(s) for Torch God's Favor event/ability unlocked.

#### Any screenshots?

Are any required? Set server-side character saving, unlock it on a character, log out, log back in with the same character. Torch God's Favor is "gone."

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?

It's not my server. I don't have logs. This issue was also reported on the Discord, but I haven't seen it logged as a defect on GitHub.

#### What plugins and what versions of those plugins are you running?

None. Vanilla setup.

**Comment by mpql** [comment]
Had this on my server, even if using the item, the corresponding toggle effect does not persist between sign-ons. I've just been spawning the item anew.

I have yet to see the torch god's attacks start up again, but I didn't thoroughly test for this.

**Comment by sk9c00** [comment]
Can confirm this (item not persisting in SSC) happening on my SSC-enabled server as well~

**Comment by QuiCM** [comment]
I believe we acknowledge application of torch god but do not apply it consistently at this point in time. We will need to add tracking for this. Thanks for reporting :)

**Comment by jzimmm** [comment]
What is the progress on this?

**Comment by Walter-o** [comment]
Happens on Pre-Release 12 too.

**Comment by jzimmm** [comment]
Do you guys need any assistance with this? I am a developer and would be happy to lend a hand.  I've worked on mods for other games a handful of times.

**Comment by Brycey92** [comment]
As far as I know, the TShock devs happily accept well-written contributions via pull requests. Check out the [Developer's Guide](https://github.com/Pryaxis/TShock#developers-guide).

**Comment by hakusaro** [comment]
This is true. I have this on my todo list. But fundamentally, a PR to fix the problem is ridiculously easy to greenlight than any other form of contribution.

Right now my life (not Chris's life -- I suggest sponsoring him on GitHub because he's usually able to handle issues with TShock far faster than me, most of the time) is really complicated, so it's not easy to allocate time to TShock right now.

But if I'm completely honest, we really kinda got hit hard with a momentum killer midway through the release process. I don't want to dive too far into the details, but suffice it to say that one tiny email would've saved everyone on the project a lot of undue stress/pressure. This was one specific factor introduced by one specific group of people that we had been operating under one assumption about for a long time. Even though the issue is now resolved, it was incredibly damaging to morale. TShock is a great project to spend lots of time working on, with lots of awesome people -- but it's not a cakewalk. It's a huge technical puzzle which creates a lot of burdens. The timing of COVID-19 with the latest update made it a great reprieve from reality until this one particular factor killed that. But the reprieve only really lasted until this event. Then it became an added stress factor, not something that helped escape from reality. Add on the fact that particularly in the US, the world got a lot more stressful for a big period of time, and presto: time + energy = removed.

So now we're here. There's a good chance that more people will "float back into working on TShock" soon. This project is eternal and most of the people who work on TShock absolutely love working on it for everyone. We've poured thousands of hours into it, after all. Most of us just have to put it on the backburner for a period of time. The difference between us and other projects is that we definitely are here, and we definitely read these messages, and we definitely do care.

I do suggest tipping a few hats towards Chris though, because he's one of the people who can usually pour more time into the project than most, more consistently.

Anyways. Fundamentally, we'll work on this. In due time, though. I'm working as hard as I can and as fast as I can on handling what's on my plate outside of TShock to get back to my real life's work: fixing Terraria.

Anyways, one of those problems just showed up. So, be right back!

**Comment by jzimmm** [comment]
Holy crap I was not expecting that type of an update but I really appreciate it. I will probably just fork the project and fix it myself and compile it for my own server. I'll submit the pull request then.

**Comment by mpql** [comment]
@hakusaro Hey, if it would help to hear, as a community member and fellow developer, I really appreciate all the work you folks put into this project. Real life will always come first, and stressors will always slow things down. We appreciate all of you, and totally understand. <3

**Comment by Brycey92** [comment]
@hakusaro Thanks for the update, and I completely understand! We love you and the other devs whether or not you're working on TShock, and hope you put your personal sanity/health/etc first. Keep being awesome! <3
