### ISSUE TITLE
Command /buff not granting summons

### ISSUE THREAD

**Issue by Survap** [Pryaxis/TShock#2188]
**TShock version: 4.4.0.0
TShock build number (if known): Pre15**

Reproduction steps (if applicable)?

1. Use **/buff** command with any summon-related buff ID (For example: 64)
2. No summon will be granted (though message from server says otherwise)

**Comment by bartico6** [comment]
Pets, Light Pets, and Mounts are limited to one - thus, giving the buff also spawns the pet.

Summons don't work like this: You can have *multiple* of each summon while maintaining just one buff, which is why the game *does not* spawn minions as a result of applying the buff (but does remove them when you rightclick it).

It's an intentional base game behaviour, and most likely will not be changed.

**Comment by Survap** [comment]
Thanks for the response.

It is clear now, and it was the buff's tooltip reference that made me assume this should be working otherwise.
