### ISSUE TITLE
Please update to ver. 1.4.2.1

### ISSUE THREAD

**Issue by BULL3TB0T** [Pryaxis/TShock#2265]

**Comment by Kojirremer** [comment]
They will when they are ready. Rushing people for no reason only accomplishes bothering them.

**Comment by BULL3TB0T** [comment]
There has been no update for almost half a year I think?

**Comment by Kojirremer** [comment]
Pretty sure the 1.4.2.x update has not been out for that long.

**Comment by BULL3TB0T** [comment]
But there weren't any updates until November.

**Comment by bartico6** [comment]
what?

**Comment by ellenjane** [comment]
Sure, they are going to do it once they are ready, that much is self-explanatory. Would it take too much time to provide this update that only added minor things, though?
Edit: Just asking a genuine question. Not trying to imply that it does not take time.

**Comment by shishioko** [comment]
heil tshock-for-1.4.2.1

**Comment by Moneylover3246** [comment]
> Sure, they are going to do it once they are ready, that much is self-explanatory. Would it take too much time to provide this update that only added minor things, though?
> Edit: Just asking a genuine question. Not trying to imply that it does not take time.

Probably not, but there's too few amount of people who know how to patch OTAPI and TerrariaServer, and fix any bugs that TShock could have from the update. And nearly everyone who knows how now has a full time job because they're in their 20s/30s and time doesn't freeze. People do this for free and this entire project is volunteer work. You can try and contribute towards TShock but remember this isn't a thing that people do for a living

**Comment by yhxaxy** [comment]
希望快点更新到1.4.2.1 阿巴阿巴 辛苦了

**Comment by tilda** [comment]
related #2266
