### ISSUE TITLE
Additional anti-cheat measures (if its even possible)

### ISSUE THREAD

**Issue by moisterrific** [Pryaxis/TShock#2391]
**Is your feature request related to a problem? Please describe.**
currently no anti-cheat/bouncer measures for: 
1. modded clients that can spawn whatever item into their inventory
2. modded/cheat clients that can somehow never die
3. edited player saves that stack multiples of the same buff
4. edited player saves that have insanely high buff durations
5. edited player saves that stack multiples of the same accessory
6. no way to ban a specific buff
7. check if the player has more than the legit possible amount of minions

**Describe the solution you'd like**
1. idk tbh
2. dunno how this can be fixed either
3. check for more than 1 of the same buff, if yes then disable or kill the player since you can't clear buffs outside of ssc
4. similar solution as above
5. check >1 of the same accessory and disable the player
6. add a new buffban feature, players would be disabled until they remove the buff on their own or by force
7. disable or kick 

**Describe alternatives you've considered**
plugins but some of these should be built into TShock imo

**Additional context**
illegal buff and accessory stacking is very common and very easy to do so it would be nice if TShock could prevent that out of the box

**Comment by bartico6** [comment]
from what I gather, bouncer is currently intended to be a simple behaviour filter for things completely impossible using a vanilla client - but only ones inexpensive and simple to test for.

with this in mind:

1. unlikely to ever be implemented by tshock, shouldnt be part of tshock
2. unlikely to ever be implemented by tshock, shouldnt be part of tshock
3. simple test, tshock/plugin territory
4. tedious gameversion specific test, plugin territory
5. simple test, tshock/plugin territory
6. could be part of tshock because itembans and projectilebans are, but ive previously heard some intent to move projbans and itembans to a plugin
7. tedious test, plugin territory

I may be completely wrong, but in that case I'm sure someone from HQ will correct me
