### ISSUE TITLE
Default ban behaviour is unintuitive because it doesn't ban by name

### ISSUE THREAD

**Issue by Mrcactus1215** [Pryaxis/TShock#2545]
!!!!!! PLEASE FILL IN THE TEMPLATE BELOW THANK YOU VERY MUCH !!!!!!

If you don't need help, delete this template and just post an issue (feature requests and discussions and the like).

* TShock version: 4.5.12.0
* TShock build number (if known): no idea

#### Reproduction steps (if applicable)?

1. Ban a player using the default ban command (/ban add [name]) (note: it's important no flags are used, as in the "intuitive" or "naïve" case)
2. Look at the console and see that a ban is never created for a name. (This is intended behavior, according to a comment in the ban function!)
3. Look at the console more, and see that the only bans created are for UUID and IP address (the ban function also suggests an account ban is added as well)
4. Regenerate the UUID (which is stored locally) by deleting the current one which is in \Documents\MyGames\Terraria\config.json.
5. Change your IP address by using a free VPN service
6. Join back as the player that was banned
7. At least on servers with functionality for "logging in" enabled, it seems that a ban check occurs, no account is associated (no login yet), UUID/IP are different and "account is null" (is this the case?), so none of the 3 default criteria are matched, and then the player is allowed in and can login (without an additional ban check!) and proceed to play unimpeded

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS no.
```

#### Any screenshots?

!!!!!! PLEASE FILL IN THE TEMPLATE ABOVE THANK YOU VERY MUCH !!!!!!
no

**Comment by QuiCM** [comment]
Bans in this game are a mess.
There are no accessible uniquely identifying characteristics that correlate to a single individual.
Banning a name is simply that - the name is banned. Any other person that ever tries to join with that name is banned.
Likewise, banning an IP simply means anyone ever using that IP will be considered banned - UUIDs are also the same.

All of these characteristics can be changed by a player more-or-less at will, so trying to tie any of them to an individual becomes meaningless.
As a result, the default ban simply adds entries for all available characteristics (except character name) in an attempt to ban as thoroughly as possible. None of these entries are correlated back to a single entity, because any of them can be adjusted at any time.

Its not ideal, because Terraria doesn't allow us any better solution. Although its probably not the answer you're looking for, in general we recommend that your 'guest' group is given as few permissions as possible & players have to login to be allowed to play

**Comment by hakusaro** [comment]
For some context we've tried to ask Re-Logic multiple times for:
1. Steam authentication (to provide a central source of identity that you can ban)
2. A central login server just like what Minecraft has, for a single central source of identity that you can ban
3. Permission to create our own auth system based on Steam to provide a central source of identity that you can ban

We have been denied on all fronts for over a decade, multiple times.

If you want to ban someone from playing on your server, either be prepared to play whack-a-mole, invent your own home-grown cheat detection system that can identify players based on their behaviors and not based on their identity, or charge people an entrance fee.

**Comment by Hextator** [comment]
None of these are answering the actual issues, which are 2-fold:
1) In an attempt to "add entries for all available characteristics" it should also ban by name, which is more like what people would expect
2) Enabling the login system to facilitate SSC doesn't seem to check for bans again at the time of login, so the ban check fails (due to "not having an account" by which to match the account ban), the player logs in and has a banned account assigned to their character, and then instead of another ban check finally booting them from the server, they can just continue playing. This makes the default behavior of banning "by account" useless. Is this not what is happening? If it is, then surely it's a bug?

**Comment by QuiCM** [comment]
Banning by name by default opens a whole new can of worms.

What if someone decides to name their character 'quicm' and comes and griefs my server. Should banning them ban myself as well? Should I be prevented from using my own chosen name?

If you ban someone who has not logged in, an account ban is not added. So if they change all of the characteristics that were available at the time of the ban, rejoin, then login, then of course the post-login ban check will not find anything to match against

**Comment by Hextator** [comment]
The example banned player IS logged in at the time of being banned, but is not logged in at the time of joining, when a ban kick normally occurs. Would this be the same concept and also fail to match the account ban? When does "account" stop being null? Why is there not another check for bans at the time of login, when the ban criteria would be able to match?

**Comment by QuiCM** [comment]
If the login before join option is on, account should be included in the ban check - if not, it will be skipped. I believe there is a post-login ban check as well (at which point account would no longer be null), but if there is not then that *is* an oversight that needs to be resolved

**Comment by Hextator** [comment]
That seems to be the case, because the test case has logins not available until after joining and entering a password with a /login command.
