### ISSUE TITLE
Change Environment.CurrentDirectory (follow up from #2670)

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#2674]
This is a follow-up item to track @Rozen4334's comment from #2670 (since we're gonna merge that for logistic reasons around CI, nuget, etc) before addressing:

<img width="923" alt="Screen Shot 2022-10-05 at 02 08 42" src="https://user-images.githubusercontent.com/532647/194024403-546ce7c0-3ad0-450f-8ad5-b46e66fce819.png">

**Comment by hakusaro** [comment]
Direct link: https://github.com/Pryaxis/TShock/pull/2670#discussion_r985829892

**Comment by SignatureBeef** [comment]
@Rozen4334 whats your thought about using `AppContext.BaseDirectory` instead of `Environment.CurrentDirectory` & `Assembly.Location`
[AppContext](https://learn.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=net-6.0), should point to the location of the assemblies for dependency resolution.

Seems to work in both debug and release builds in the current tshock setup, but i do not often use startup files either.

**Comment by SignatureBeef** [comment]
Also secondary note, i think TSAPI might also need a change where [ServerApi](https://github.com/Pryaxis/TSAPI/blob/36bcd9594cc0406d34393dac5e7e806c2c4ea66e/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs#L93) uses Environment.CurrentDirectory, too.

**Comment by csmir** [comment]
This is a good solution. according to the documentation it also works in bundled, so should be perfect
