### ISSUE TITLE
Potential issue: quick stack deletes all items?

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TShock#2707]
![A7A75AAC-10D0-4FFE-9880-B9CAE3752072](https://user-images.githubusercontent.com/532647/194745720-079bd66f-97f3-47aa-815b-4635d679fac8.png)

It’s unclear to me if this is a TShock or vanilla problem.

**Comment by SignatureBeef** [comment]
Im not sure if this is directly relatable, but OTAPI 3.1.11-alpha addresses a [Quick stack to near by chests] bug, where in my own testing, it did not work at all due to the hook being invoked to a incorrect chest index. If this is the same bug, the items are likely to be in another (seemingly) random chest.
