### ISSUE TITLE
Be able to copy SSC data

### ISSUE THREAD

**Issue by TostadoraZD** [Pryaxis/TShock#2922]
If the only thing we can do in the SSC (Server Side Characters) configuration is to be able to activate it, deactivate it, change the items with which to start on the server, etc., why not be able to copy or save the inventory data of the players to later paste them on other servers easily like any file or something like that? so when players enter another server that had the SSC data added there and log into that other server they will have the same anti-cheat SSC inventory from the previous server... or if that is possible right now and I don't know how, please let me know so I don't look ridiculous writing all this : ].

**Comment by Arthri** [comment]
At the moment, it's not possible to make the Terraria client do this. You would have to establish a network with other servers for SSC data transfer

**Comment by sgkoishi** [comment]
Everyone can set up their own server, spawn whatever item as admin and copy-paste to other servers, so TShock won't allow regular players to do so by default.

Data is stored in the database, you can of course copy the database file to another server (only if you have operator access to both servers).

**Comment by TostadoraZD** [comment]
Where can i find the "database"?

**Comment by sgkoishi** [comment]
By default `tshock.sqlite`. All user accounts, inventories, groups, permissions, etc. are stored.

**Comment by TostadoraZD** [comment]
:o

**Comment by drunderscore** [comment]
As answered above, `tshock.sqlite` contains a table called `tsCharacters`, which will contain the SSCs of all TShock accounts. You can use this to transfer to other servers, but TShock cannot be configured on it's own to do anything as such.

Also as noted above, a higher-level network abstraction/proxy would likely be needed in order to share inventory between multiple TShock servers.
