### ISSUE TITLE
Mobile server hosting

### ISSUE THREAD

**Issue by ghost** [Pryaxis/TShock#2973]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
This to be set up on mobile devices (IOS, Andriod, etc)

**Describe alternatives you've considered**
Something that you can use to make a tshock server on github

**Additional context**
The server has to be able to run when the app is closed (background running)^1
The console has to be mobile friendly
The server creator needs to have terraria installed (suggested)
Be optimized to where the mobile users can host it without breaking their phone

^1 the server must shutdown when requested

**Comment by sgkoishi** [comment]
There are cases where people host the server with Android and works. You can try to follow their steps, but there will be no support.

**Comment by ghost** [comment]
> There are cases where people host the server with Android and works. You can try to follow their steps, but there will be no support.

@sgkoishi to be honest i use a apple device...

**Comment by pcider** [comment]
You can host a TShock server on Android using Termux, and I guess something similar to Termux exists on iOS devices. Once you get the terminal, the steps are pretty much the same as hosting on PC since TShock is GUI-less. You may have to work around issues like terminated background processes. (You're off on your own then since we provide support for TShock only)

**Comment by ghost** [comment]
Thank you @PotatoCider
