### ISSUE TITLE
Build Permission for Old one army

### ISSUE THREAD

**Issue by D3RKDUDE** [Pryaxis/TShock#2977]
I saw the list of Tshock commands and accesses, and it seems that there is no way to build or dig in the Old One Army event.  Is it possible to add a feature in the future so that we can continue to build in this event?

**Comment by Arthri** [comment]
Build permissions in the event Old One's Army is regulated by the client rather than the server. So no, TShock can not change that

**Comment by ghost** [comment]
Yes, there is a command that can do that... it removes the effect but you have to do it every second... it WOULD be helpful if they added a new configuration option so @Arthi this IS monitored by the server by the server adding a "building barrier"... you would also have to turn this off by editing game code or server code...
________________________________
From: Mohammad Reza Ghorbani ***@***.***>
Sent: Wednesday, October 4, 2023 11:18 AM
To: Pryaxis/TShock ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Pryaxis/TShock] Build Permission for Old one army (Issue #2977)


I saw the list of Tshock commands and accesses, and it seems that there is no way to build or dig in the Old One Army event. Is it possible to add a feature in the future so that we can continue to build in this event?

**Comment by Arthri** [comment]
The buff is purely aesthetic: anti-build is enforced by the `Player.noBuilding` field, which itself is enforced by `DD2Event.Ongoing`. The checks happen early on in `Player.Update` and before `ItemCheck` runs. So even if the buff were removed, it would be force applied before building code runs anyway

**Comment by D3RKDUDE** [comment]
So maybe we have

**Comment by ghost** [comment]
why was it reopened @ghorbani?
________________________________

**Comment by D3RKDUDE** [comment]
Cause i cant see any solution or way for it. Do you know how can i do it?

**Comment by ghost** [comment]
try modding the terraria server software _**THIS IS NOT SUGGESTED**_

**Comment by Arthri** [comment]
That's what TShock is: a server mod. I've said before that this is a *client* restriction, *not* a *server* restriction

**Comment by D3RKDUDE** [comment]
So my summary of what we know is: we can't have a permission to be able to build and dig in old one army event.

**Comment by ghost** [comment]
correct
________________________________

**Comment by drunderscore** [comment]
Closing as this feature request is not possible to implement.
